# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

cache:
  paths:
  - node_modules/

test_async:
  script:
   - npm install
   - npm install --global mocha
   - npm run test

test_coverage:
  script:
    - npm install
    - npm install --global mocha nyc
    - npm run coverage
