language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

stages:
  - test
  - name: deploy
    if: branch = master

before_install:
  - npm i -g mocha nyc

deploy:
  - provider: script
